---
name: MooseFS
version: 0.1
slug: moosefs
description: Mount a MooseFS share on Home Assistant, expose the MooseFS GUI, and export the mount over NFSv4
url: https://github.com/Akm0d/hassio-app-moosefs
startup: services
boot: auto
init: false
ingress: true
ingress_port: 8099
ingress_entry: /mfs.cgi
apparmor: true
hassio_api: true
hassio_role: admin
panel_icon: mdi:cow
webui: http://[HOST]:[PORT:9425]/mfs.cgi
panel_title: MooseFS
arch:
  - aarch64
  - amd64
devices:
  - /dev/fuse
privileged:
  - SYS_ADMIN
ports:
  2049/tcp: 2049
  9425/tcp: 9425
ports_description:
  2049/tcp: MooseFS NFSv4 Export
  9425/tcp: MooseFS GUI Direct
options:
  log_level: info
  master_host: ""
  master_port: 9421
  master_subfolder: /
  master_password: ""
  mount_point: /mnt/mfs
  backup_dir: ""
  media_dir: ""
  share_dir: /
  mount_enabled: true
  delayed_init: true
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)
  master_host: str
  master_port: int(1,65535)
  master_subfolder: match(^/.*$)
  master_password: str
  mount_point: match(^/.+$)
  backup_dir: str
  media_dir: str
  share_dir: str
  mount_enabled: bool
  delayed_init: bool
