---
name: MooseFS
version: 0.1
slug: moosefs
description: Mount a MooseFS share on Home Assistant and expose the MooseFS GUI
url: https://moosefs.com/about
startup: services
boot: auto
init: false
ingress: true
ingress_port: 8099
ingress_entry: /mfs.cgi
apparmor: false
panel_icon: mdi:cow
webui: http://[HOST]:[PORT:9425]/mfs.cgi
panel_title: MooseFS
panel_icon: mdi:folder-network
apparmor: false
arch:
  - aarch64
  - amd64
devices:
  - /dev/fuse
privileged:
  - SYS_ADMIN
ports:
  9425/tcp: 9425
ports_description:
  9425/tcp: MooseFS GUI Direct
map:
  - media:rw
  - share:rw
  - ssl
options:
  log_level: info
  master_host: ""
  master_port: 9421
  master_subfolder: /
  master_password: ""
  mount_point: /share/mfs
  mount_enabled: true
  delayed_init: true
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)
  master_host: str
  master_port: int(1,65535)
  master_subfolder: match(^/.*$)
  master_password: str
  mount_point: match(^/.+$)
  mount_enabled: bool
  delayed_init: bool
